[package]
name = "actix-rust"
version = "1.0.0"
description = ""
authors = ["Dimas Yudha Pratama"]
license = "MIT"
repository = "https://github.com/pingdimasyudha/actix-rust"
edition = "2021"
rust-version = "1.77.2"

[dependencies]
actix-web = "4"